server:
  port: 8080

spring:
  application:
    name: food-gateway
  config:
    import: "optional:nacos:"
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        enabled: false
    gateway:
      routes:
        # 用户服务
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=0

        # 拼单服务
        - id: pool-service
          uri: lb://pool-service
          predicates:
            - Path=/api/v1/pools/**
          filters:
            - StripPrefix=0

        # 订单服务
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=0

        # 支付服务
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - StripPrefix=0

        # 商家服务
        - id: merchant-service
          uri: lb://pool-service
          predicates:
            - Path=/api/v1/merchants/**
          filters:
            - StripPrefix=0

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
